### ISSUE TITLE
Support for equivalent to `Bufferline`'s `BufferLinePick` and `BufferLinePickClose`

### ISSUE THREAD

**Issue by ofk-enterprise-account** [noib3/nvim-cokeline#16]
First, let me say what a cool project.
As an avid user of `Bufferline` I like that "competition" is happening with each having its own set of cool features and implementation that the others then implement, so on, so forth.
Kudos!

To the point: `Bufferline` has two great features, listed in the title: `BufferLinePick` which, when triggered displays a sigil on each buffer that lets you do a one-click goto to **any** buffer (more so: since the sigils are unique and constant per session, if you know the sigil of a buffer not displayed on the buffer line itself, you can trigger the function and go to the hidden buffer by its sigil... hidden or not).

`BufferLinePickClose`, as you can imagine, does the same as its non-destructive counterpart, but closes the selected buffer, allowing for pinpoint closing of buffers without first having to switch over to them and then `:bdelete`.

More than any visual candy, I, personally, find these two functions to be indispensable, now that I started using them.
It would be great if, **at some point**, `cokeline` could have them too.

And, again, great project.
Looking really, really cool!
(BTW, if you need "inspiration", 😆, another cool, up-and-coming buffer line plugin is `barbar`).

**Comment by noib3** [comment]
> First, let me say what a cool project.
As an avid user of Bufferline I like that "competition" is happening with each having its own set of cool features and implementation that the others then implement, so on, so forth.
Kudos!

Thanks!

I had thought about implementing this some time ago, what stopped was not being how the users would enable/configure this behaviour given `cokeline.nvim`'s component-based configuration.

For example take this very basic configuration:
```lua
local get_hex = require('cokeline/utils').get_hex

local space = {
  text = ' '
}

local devicon = {
  text = function(buffer) return buffer.devicon.icon end,
  hl = {
    fg = function(buffer) return buffer.devicon.color end,
  },
}

local filename = {
  text = function(buffer) return buffer.filename .. ' ' end,
}

local close_button =  {
  text = '',
  delete_buffer_on_left_click = true,
}

require('cokeline').setup({
  default_hl = {
    focused = {
      fg = get_hex('ColorColumn', 'bg'),
      bg = get_hex('Normal', 'fg'),
    },
    unfocused = {
      fg = get_hex('Normal', 'fg'),
      bg = get_hex('ColorColumn', 'bg'),
    },
  },

  components = {
    space,
    devicon,
    filename,
    close_button,
    space,
  },
})
```
which looks like this
![cokeline-default](https://user-images.githubusercontent.com/59321248/140792901-89a79a3e-1e0d-429c-9a4c-1788abb9998a.png)

A possible way to enable such behaviour would be to provide two functions, let's call them `is_picking_focus()` and `is_picking_close()` (I'm bad at names, tell me if you have better ideas) that return `True` when the user is picking a buffer to focus or to close. Also, the `buffer` table would have to provide a `buffer.pick_symbol`.

To actually display the pick symbol we could modify the `devicon` component to either show the devicon (if both `is_picking_focus()` and `is_picking_close()` return false) or the pick symbol. Simply adding a new component would cause all the lines to change width when we're picking a buffer to either focus or close, which would look weird.

With all this in mind, the devicon component would become
```lua
local pickers = require('cokeline/pickers')
local is_picking_focus = pickers.is_picking_focus
local is_picking_close = pickers.is_picking_close

-- ...
local devicon = {
  text = function(buffer)
    if is_picking_focus() or is_picking_close() then
      return buffer.pick_symbol
    end
    return buffer.devicon.icon
  end,
  hl = {
    fg = function(buffer)
    if is_picking_focus() then
      return 'yellow'
    else if is_picking_close() then
      return 'red'
    end
    return buffer.devicon.color
    end,
  },
}

-- ...
```

This could be a way to go about it, but like I said I'm not sure it's the best one. Any feedback?

**Comment by noib3** [comment]
Hi, I've finally added this feature. Check out the [Buffer pick](https://github.com/noib3/nvim-cokeline#buffer-pick) and [Mappings](https://github.com/noib3/nvim-cokeline#musical_keyboard-mappings) sections of the README for instructions on how to add this to your config.
