### ISSUE TITLE
Offset for NvimTree?

### ISSUE THREAD

**Issue by krims0n32** [noib3/nvim-cokeline#31]
Hi! Thank you for writing and releasing your plugin.

I have a question, what would be the best approach to have the bar have an offset when NvimTree is opened? Bufferline and others are able to detect this and have the output above the buffer only, not above the NvimTree window.

Not a biggie, but a nice to have perhaps.

**Comment by noib3** [comment]
Hi, I'm aware cokeline is currently lacking this feature and I plan to add it before the end of the year.

**Comment by mgokbulut** [comment]
Also looking forward to this enhancement 👍

**Comment by noib3** [comment]
> ... and I plan to add it before the end of the year.

Well, almost ;) 

`nvim-cokeline` now supports setting left and right sidebars. Check out the README for the relative config options and an example config that implements them.
