### ISSUE TITLE
Getting white background where there are no buffers

### ISSUE THREAD

**Issue by tamirzb** [noib3/nvim-cokeline#38]
Basically like the title says. This is how it looks:

![image](https://user-images.githubusercontent.com/1054209/147596451-4f9b16d4-b4d1-4202-8ca3-0599bc2a8b16.png)

How can I get the rest of the line to have the same background as the buffers? I'm assuming I miss a configuration/setting a highlight group but I couldn't find anything in the documentation about this.

**Comment by noib3** [comment]
We leave that to the users. You can configure it with the `TabLineFill` highlight group.

**Comment by tamirzb** [comment]
I see, thanks!

Perhaps it could be useful to document this somewhere?

**Comment by noib3** [comment]
> Perhaps it could be useful to document this somewhere? (or is this documented somewhere I missed?)

No, it's not documented anywhere atm.

I was thinking about making cokeline set that highlight group automatically blend in to `default_hl.unfocused`, i.e. the same foreground and background colors of non focused buffers.
