### ISSUE TITLE
Buffer Limit?

### ISSUE THREAD

**Issue by krims0n32** [noib3/nvim-cokeline#41]
My neovim tends to get sluggish with many buffers open (>15), which happens pretty fast when coding. What would be the best way to auto-close "old" buffers when opening a new one? Is this something this plugin could do or do I need to do some hacking elsewhere?

Thanks again for your awesome plugin, does the job perfectly!

**Comment by noib3** [comment]
Closing "old" buffers (whatever the logic used to determine if a buffer is old might be) is definitely out of the scope of this plugin.

You could write a function that closes the oldest buffer if there are more than 15 buffers opened and execute it everytime a new buffer is opened with an autocmd, something like
```lua
_G.close_oldest_buffer_or_cpu_will_explode = function()
  -- ...
end

vim.cmd('autocmd BufAdd * silent call v:lua.close_oldest_buffer_or_cpu_will_explode()')
```
