### ISSUE TITLE
Default highlighting overrides highlighting for specific components

### ISSUE THREAD

**Issue by jonathansharpe** [noib3/nvim-cokeline#42]
I was trying to configure my setup, when I realized trying to change the highlights of certain elements was just not working. Here's my config for an example:

```lua
local is_picking_focus = require('cokeline/mappings').is_picking_focus
local is_picking_close = require('cokeline/mappings').is_picking_close
local get_hex = require('cokeline/utils').get_hex

local components_cokeline = {
	space = {
		text = ' ',
	},
	separator_left = {
		text = function(buffer)
			return buffer.index == 1 and '' or ''
		end,
		hl = {
			focused = {
				fg = '#ff0000',
				bg = '#00ffff',
			},
			unfocused = {
				fg = '#00ffff',
				bg = '#ff0000',
			},
		},
	},
	separator_right = {
		text = '',
		hl = {
			unfocused = {
				fg = get_hex('Comment', 'fg'),
				bg = get_hex('ColorColumn', 'bg'),
			},
			focused = {
				fg = get_hex('ColorColumn', 'fg'),
				bg = get_hex('Normal', 'bg'),
			},
		},
	},
	devicon = {
		text = function(buffer)
			return
			(is_picking_focus() or is_picking_close())
			and buffer.pick_letter .. ' '
			or buffer.devicon.icon
		end,
		hl = {
			fg = function(buffer)
				return
				(is_picking_focus() and yellow)
				or (is_picking_close() and red)
				or buffer.devicon.color
			end,
			style = function(_)
				return
				(is_picking_focus() or is_picking_close())
				and 'italic,bold'
				or nil
			end,
		}
	},
	index = {
		text = function(buffer)
			return buffer.index .. ': '
		end,
	},
	filename = {
		text = function(buffer) return buffer.filename .. '  ' end,
		hl = {
			style = function(buffer)
				return buffer.is_focused and 'bold' or nil
			end,
		}
	},
	close_button = {
		text = '',
		delete_buffer_on_left_click = true,
    },
}

require('cokeline').setup({
	default_hl = {
		focused = {
			fg = '#ffff00',
			bg = '#ff00ff',
		},
		unfocused = {
			bg = '#ffff00',
			fg = '#ff00ff',
		},
	},
	components = {
		components_cokeline.separator_left,
		components_cokeline.space,
		components_cokeline.devicon,
		components_cokeline.space,
		components_cokeline.index,
		components_cokeline.filename,
		components_cokeline.space,
		components_cokeline.separator_right,
	},
})
```

In the `hl` section for the `separator_left` component, I chose red and cyan as the foreground and background respectively. However, here's a screenshot of what actually happens:

![image](https://user-images.githubusercontent.com/85899821/152705755-94d3d9eb-fe56-432e-bb3b-440d7577ebb4.png)

Instead, cokeline chooses the default colors here instead of the ones I specified in the `separator_left` component. Either I'm configuring this incorrectly, or there's a bug in the plugin.

**Comment by noib3** [comment]
> Either I'm configuring this incorrectly, or there's a bug in the plugin.

The first one. Only `default_hl` takes the `focused` and `unfocused` keys. A component's `hl` table only takes `fg`, `bg` and `style` as keys, so `separator_left` and `separator_right` are configured incorrectly. The other components are fine.

If you want a component to have different colors depending on if the buffer it's in is focused/unfocused, do what you've done in `devicon.hl.fg`. Pass a function that takes the buffer as parameter and returns different values depending on `buffer.is_focused`.

**Comment by jonathansharpe** [comment]
Ah I see. I've piecemealed this together from other configs to try and learn it. Thanks for your help!
