### ISSUE TITLE
Conflicts with neogit

### ISSUE THREAD

**Issue by aperum** [noib3/nvim-cokeline#43]
Every action in neogit which modifies the view throws this error:

Error detected while processing BufUnload Autocommands for "*":
E5108: Error executing lua ...ack/packer/start/nvim-cokeline/lua/cokeline/augroups.lua:34: Vim(buffer):E937: Attempt to dele
te a buffer that is in use
stack traceback:
        [C]: in function 'cmd'
        ...ack/packer/start/nvim-cokeline/lua/cokeline/augroups.lua:34: in function 'focus_on_delete'
        [string ":lua"]:1: in main chunk
        [C]: in function 'nvim_buf_delete'
        .../site/pack/packer/start/neogit/lua/neogit/lib/buffer.lua:85: in function 'close'
        ...m/site/pack/packer/start/neogit/lua/neogit/lib/popup.lua:61: in function 'close'
        ...m/site/pack/packer/start/neogit/lua/neogit/lib/popup.lua:215: in function 'cb'
        .../site/pack/packer/start/neogit/lua/neogit/lib/buffer.lua:301: in function <.../site/pack/packer/start/neogit/lua/
neogit/lib/buffer.lua:300>
        .../packer/start/neogit/lua/neogit/lib/mappings_manager.lua:9: in function 'invoke'
        [string ":lua"]:1: in main chunk

**Comment by aperum** [comment]
The culprit seems to be: focus_on_delete = "prev". I tried adding neogitstatus to filter_valid but  that did not change the error.

**Comment by noib3** [comment]
Hi, sorry for the late reply I had totally forgot about this. It should be fixed now, let me know if you still experience any problems.
