### ISSUE TITLE
Attempt to index upvalue 'keymap' (a nil value)

### ISSUE THREAD

**Issue by olimorris** [noib3/nvim-cokeline#48]
Just upgraded to `0.3` and getting this error:

```lua
packer.nvim: Error running config for cokeline.nvim: ...ack/packer/start/cokeline.nvim/lua/cokeline/mappings.lua:89: attempt to index upvalue 'keymap' (a nil value)
```

My config is:

```lua
require("cokeline").setup()
```

**Comment by noib3** [comment]
What's your neovim version?

**Comment by olimorris** [comment]
I'm on `0.6.1`. Sorry, should have said

**Comment by noib3** [comment]
What does `:h vim.keymap` say?

**Comment by olimorris** [comment]
A big fat `E149: Sorry, no help for vim.keymap`. Is `nightly` the requirement now?

**Comment by noib3** [comment]
Try the latest commit.

**Comment by olimorris** [comment]
Baby, we're back! Thanks for fixing so quickly. Pretty minimal config change for me with `0.3`
