### ISSUE TITLE
Buffers are now duplicated

### ISSUE THREAD

**Issue by olimorris** [noib3/nvim-cokeline#49]
With `0.3`, I notice that my components are now duplicated:

![Screen Shot 2022-03-06 at 12 56 50@2x](https://user-images.githubusercontent.com/9512444/156924233-231e8b1b-6e96-4d47-9bd3-8fbd3b2ea983.png)

My config is:

```lua
local M = {}

function M.setup()
    require("cokeline").setup({
        components = {
            {
                text = function(buffer)
                    return buffer.filename .. " "
                end,
            },
        },
    })
end

return M

```

**Comment by noib3** [comment]
Well that's weird. I just downgraded to nvim 0.6.1 and using that same config I can't replicate the issue.

**Comment by olimorris** [comment]
I've just done a downgrade to `f9f8e70` and it works just fine. Shall investigate further.

**Comment by noib3** [comment]
Can you test this on nightly? It might also be a weird interaction with some other plugin you're using. I can't really fix it if I can't reproduce it.

**Comment by olimorris** [comment]
Okay got it. I have an `autocmd` which reloads my cokeline setup on a colorscheme change. In `0.3`, this causes cokeline to  stack components as we see in the screenshot.

So purely my error and I'll find a way to solve. Sorry for the inconvenience.

**Comment by noib3** [comment]
Well that shouldn't happen. Can you post that autocommand?

**Comment by olimorris** [comment]
```lua
  om.augroup("RefreshBufferlineColors", {
    {
      events = { "ColorScheme" },
      targets = { "*" },
      command = function()
        require(config_namespace .. ".plugins.bufferline").setup()
      end,
    },
  })
```

The `augroup` function can be found [here](https://github.com/olimorris/dotfiles/blob/main/.config/nvim/lua/Oli/core/utils.lua). I also notice running `PackerSync` causes the issues.
