### ISSUE TITLE
[Question] When was nvim-cokeline renamed, why and will it affect existing use of it in configurations?

### ISSUE THREAD

**Issue by miversen33** [noib3/nvim-cokeline#78]
It looks like `nvim-cokeline` was silently renamed to `nvim-bufferline`. I don't have any issues with this one way or another, but it would have been nice to get a notification (either via an update to the repo ahead of time informing users this was going to happen, a post on `/r/neovim`, etc). 

Additionally, (IMO) it would make sense to update the Readme to inform users that this was in fact a previously named repo (as there are still links/blogs/etc that refer to the project by its now former name). 

And lastly for curiosity sake, what prompted the rename?

**Comment by noib3** [comment]
the rename was temporary that's why I didn't bother to make a post/update the README
