### ISSUE TITLE
Sidebar width is set wrong

### ISSUE THREAD

**Issue by ObsidianChickenz** [noib3/nvim-cokeline#80]
Whenever I open NvimTree, the bar will add one less character than necessary to cover the top of the sidebar.
[Sidebar closed](https://imgur.com/a/5NZVaj0)
[Sidebar opened](https://imgur.com/a/mbKy70L)
I'm thinking this should be an easy fix.

**Comment by noib3** [comment]
already discussed [here](https://github.com/noib3/nvim-cokeline/pull/57#issuecomment-1108656200)

**Comment by colin-heffernan** [comment]
How would I go about linking VertSplit to Normal, like you suggest?

**Comment by ObsidianChickenz** [comment]
Since this is a theme-based issue, I'm closing this.
