### ISSUE TITLE
QUESTION: Move buffer left/right?

### ISSUE THREAD

**Issue by ckt114** [noib3/nvim-cokeline#85]
Hi,

Is there a way to move the buffer left/right? I’ve read the docs but didn't see a way to do so. Thanks.

**Comment by noib3** [comment]
You can switch a buffer w/ the previous or next buffer, or with any other buffer by mapping `<Plug>(cokeline-switch-prev)`, `<Plug>(cokeline-switch-next)`, `<Plug>(cokeline-switch-i)`. See [Mappings](https://github.com/noib3/nvim-cokeline#musical_keyboard-mappings) for more infos.
